### ISSUE TITLE
Update PlatformIO to latest (4.4 as of writing)

### ISSUE THREAD

**Issue by rbray89** [platformio/platformio-registry#7] opened 2022-02-04 23:02 UTC
https://registry.platformio.org/tools/platformio/framework-espidf should be update to the latest release of esp-idf (4.4 as of writing)

**Comment by ivankravets** [comment] 2022-02-05 12:57
Duplicate of https://github.com/platformio/platform-espressif32/issues/710

Please vote for https://github.com/platformio/platform-espressif32/issues/710

**Closed as completed by ivankravets** 2022-02-05 12:57 UTC
