### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by moumou2105** [platformio/platformio-registry#60] opened 2023-04-22 11:17 UTC
# Page
https://registry.platformio.org/platforms/platformio/espressif32/insights/dependencies?version=5.1.1&p=2

# Stack
```
at P (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:164658)
    at I (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:165119)
    at D (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:477580)
    at P (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:480068)
    at Suspense
    at div
    at div
    at U (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:165975)
    at D (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:477580)
    at P (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:480068)
    at Suspense
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:187126)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:190018)
    at D (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:477580)
    at T (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:479418)
    at L (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:637857)
    at D (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:477580)
    at P (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:480068)
    at L (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:479481)
    at c (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:471903)
    at c.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:588222)
    at R (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:636723)
    at I (https://cdn.registry.platformio.org/static/js/main.9d25fafe.js:2:638051)
```

**Comment by ivankravets** [comment] 2023-04-22 11:38
Duplicate of https://github.com/platformio/platformio-registry/issues/59

**Closed as completed by ivankravets** 2023-04-22 11:38 UTC
