### ISSUE TITLE
[Error] NotFoundError: Node.removeChild: The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by ymkfqtbl2** [platformio/platformio-registry#32] opened 2022-10-13 07:53 UTC
# Page
https://registry.platformio.org/libraries/bitluni/bitluni%20ESP32Lib/installation

# Stack
```
O@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:457010
Suspense
div
div
Q@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:152703
div
main
X@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:155477
F@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456260
R@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:611100
O@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:457010
B@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456510
b@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:447940
2122/Q<@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:562188
L@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:609966
I@https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:611294
```

**Comment by ivankravets** [comment] 2022-10-31 10:38
Duplicate of https://github.com/platformio/platformio-registry/issues/33

**Closed as completed by ivankravets** 2022-10-31 10:38 UTC
